"""Add course, chapter, question models

Revision ID: 6a42b5d01b16
Revises: 
Create Date: 2025-12-03 00:20:50.656104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a42b5d01b16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('chapters', sa.Column('order_index', sa.Integer(), nullable=False))
    op.drop_column('chapters', 'name')
    op.add_column('courses', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_constraint('courses_name_key', 'courses', type_='unique')
    op.drop_column('courses', 'name')
    op.add_column('questions', sa.Column('options', sa.JSON(), nullable=False))
    op.add_column('questions', sa.Column('correct_answer', sa.String(length=255), nullable=False))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.alter_column('questions', 'chapter_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('questions_course_id_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_chapter_id_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_correct_option_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'course_id')
    op.drop_column('questions', 'correct_option_id')
    op.drop_column('questions', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('source', postgresql.ENUM('generated', 'past_paper', 'manual', name='question_source'), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('correct_option_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_correct_option_id_fkey', 'questions', 'options', ['correct_option_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('questions_chapter_id_fkey', 'questions', 'chapters', ['chapter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('questions_course_id_fkey', 'questions', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('questions', 'chapter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'options')
    op.add_column('courses', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('courses_name_key', 'courses', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('courses', 'title')
    op.add_column('chapters', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('chapters', 'order_index')
    op.drop_column('chapters', 'title')
    # ### end Alembic commands ###

